/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsCedarHollowRouteImport } from './routes/tools.cedar-hollow'
import { Route as SolutionsAudienceRouteImport } from './routes/solutions.$audience'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCedarHollowRoute = ToolsCedarHollowRouteImport.update({
  id: '/cedar-hollow',
  path: '/cedar-hollow',
  getParentRoute: () => ToolsRoute,
} as any)
const SolutionsAudienceRoute = SolutionsAudienceRouteImport.update({
  id: '/solutions/$audience',
  path: '/solutions/$audience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$audience': typeof SolutionsAudienceRoute
  '/tools/cedar-hollow': typeof ToolsCedarHollowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$audience': typeof SolutionsAudienceRoute
  '/tools/cedar-hollow': typeof ToolsCedarHollowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRouteWithChildren
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/solutions/$audience': typeof SolutionsAudienceRoute
  '/tools/cedar-hollow': typeof ToolsCedarHollowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/tools'
    | '/product/$slug'
    | '/solutions/$audience'
    | '/tools/cedar-hollow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/tools'
    | '/product/$slug'
    | '/solutions/$audience'
    | '/tools/cedar-hollow'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/methodology'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/security'
    | '/tools'
    | '/product/$slug'
    | '/solutions/$audience'
    | '/tools/cedar-hollow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MethodologyRoute: typeof MethodologyRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  SolutionsAudienceRoute: typeof SolutionsAudienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cedar-hollow': {
      id: '/tools/cedar-hollow'
      path: '/cedar-hollow'
      fullPath: '/tools/cedar-hollow'
      preLoaderRoute: typeof ToolsCedarHollowRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/solutions/$audience': {
      id: '/solutions/$audience'
      path: '/solutions/$audience'
      fullPath: '/solutions/$audience'
      preLoaderRoute: typeof SolutionsAudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof ProductRoute
    }
  }
}

interface ProductRouteChildren {
  ProductSlugRoute: typeof ProductSlugRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductSlugRoute: ProductSlugRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

interface ToolsRouteChildren {
  ToolsCedarHollowRoute: typeof ToolsCedarHollowRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCedarHollowRoute: ToolsCedarHollowRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MethodologyRoute: MethodologyRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRouteWithChildren,
  SecurityRoute: SecurityRoute,
  ToolsRoute: ToolsRouteWithChildren,
  SolutionsAudienceRoute: SolutionsAudienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
